"""fix value

Revision ID: 6d390803ef6f
Revises: 96ef6803706d
Create Date: 2025-09-05 17:39:51.369061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d390803ef6f'
down_revision: Union[str, Sequence[str], None] = '96ef6803706d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'limit',
               existing_type=sa.NUMERIC(precision=10, scale=5),
               type_=sa.Numeric(precision=30, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'limit',
               existing_type=sa.Numeric(precision=30, scale=0),
               type_=sa.NUMERIC(precision=10, scale=5),
               existing_nullable=True)
    # ### end Alembic commands ###
