"""second

Revision ID: a188668a7941
Revises: 8a23750dd467
Create Date: 2025-09-05 15:46:38.313869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a188668a7941'
down_revision: Union[str, Sequence[str], None] = '8a23750dd467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults',
    sa.Column('id', mysql.BIGINT(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('last_30_days_apr', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('exposure', sa.Numeric(precision=25, scale=6), nullable=True),
    sa.Column('numberOfDepositors', sa.Integer(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('profit_share', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaults'))
    )
    op.add_column('users', sa.Column('limit', sa.Numeric(precision=10, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'limit')
    op.drop_table('vaults')
    # ### end Alembic commands ###
